#!/usr/bin/env python3
"""
initialize-config.py

Write the user-level `write-a-skill.yaml` configuration file.

The script prints the proposed configuration and refuses to write unless
`--approve` is passed. The conductor must obtain explicit user approval
before invoking this script with `--approve`.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

DEFAULT_REGISTRIES = ["github.com/wianvdm/skills"]

CONFIG_TEMPLATE = """# write-a-skill configuration
# Generated by scripts/initialize-config.py

# Directory containing the canonical skill-standards wiki.
# If this directory is missing, the skill will fall back to embedded docs
# and warn the user that some checks are unavailable.
standards_path: {standards_path}

# Skill registries to search when exploring alternatives.
registries:
{registries}
"""


def build_config(args: argparse.Namespace) -> dict:
    registries = [r.strip() for r in args.registries.split(",") if r.strip()]
    return {
        "config_dir": args.config_dir,
        "context_dir": args.context_dir,
        "standards_path": args.standards_path,
        "registries": registries,
    }


def format_registries(registries: list[str]) -> str:
    if not registries:
        return "  []"
    lines = []
    for r in registries:
        lines.append(f"  - {r}")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Initialize write-a-skill configuration file.",
    )
    parser.add_argument(
        "--config-dir",
        required=True,
        help="Directory where write-a-skill.yaml will be written.",
    )
    parser.add_argument(
        "--context-dir",
        required=True,
        help="Directory where context reports are written.",
    )
    parser.add_argument(
        "--standards-path",
        default="",
        help="Path to the canonical docs/skill-standards/ directory.",
    )
    parser.add_argument(
        "--registries",
        default=",".join(DEFAULT_REGISTRIES),
        help="Comma-separated list of skill registries.",
    )
    parser.add_argument(
        "--approve",
        action="store_true",
        help="Write the file after the user has explicitly approved.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Emit machine-readable output.",
    )
    args = parser.parse_args()

    config_dir = Path(args.config_dir).resolve()
    config_path = config_dir / "write-a-skill.yaml"
    config = build_config(args)

    proposed = CONFIG_TEMPLATE.format(
        standards_path=config["standards_path"] or "",
        registries=format_registries(config["registries"]),
    )

    if not args.approve:
        report = {
            "status": "needs_approval",
            "config": config,
            "config_path": str(config_path),
            "proposed_yaml": proposed,
            "message": (
                "Configuration proposal generated. Run again with --approve "
                "after the user has explicitly confirmed."
            ),
        }
        if args.json:
            print(json.dumps(report, indent=2))
        else:
            print("Proposed configuration:")
            print("-" * 40)
            print(proposed)
            print("-" * 40)
            print(f"Would write to: {config_path}")
            print("Run with --approve to write after explicit user confirmation.")
        return 0

    config_dir.mkdir(parents=True, exist_ok=True)
    config_path.write_text(proposed, encoding="utf-8")

    report = {
        "status": "written",
        "config": config,
        "config_path": str(config_path),
        "message": f"Configuration written to {config_path}.",
    }
    if args.json:
        print(json.dumps(report, indent=2))
    else:
        print(f"Configuration written to {config_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
